### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/plugin-wordpress#24]
How does the plugin works for you? For me this is how:
1. Install
2. VIsit plugin page. Its empty. Not good
3. I click on Analyze thinking it will populate. Nothing happens
4. I go to the main site and back. 5 files appear
5. On every refresh of the main site 5-6 files appear in settings. 
6. It takes me 10+ refreshes of the site to final populate the full table and manually click on Analyze to populate the URLs
7. I am finally done

That's not a good flow. Am I missing something? If not then we need to fix this

**Comment by MartinKolarik** [comment]
This is mostly correct. Technically it's fully automated so you don't need to do anything after step 1 - unless you are curious and want so see how many files it found immediately. We just need to make sure people understand that:
 - either they don't have to do anything
 - or they have to browse the website a little (or just wait 10 minutes if it's popular enough), and only then go to the plugin settings

**Comment by jimaek** [comment]
I am certain that all users after installing will go to settings and try to understand what to do next.
Maybe after installing instead of showing the table we can show a big loading animation counting down from 2 minutes and a text explaining to wait while we are gathering data.
But the counter should actually work and block the settings page only for 2 minutes

**Comment by MartinKolarik** [comment]
Problem is even that wouldn't work on smaller/testing sites that don't have active visitors. I'd say some instructions should be in the settings page but not sure about the countdown.

**Comment by jimaek** [comment]
We could send our own requests to the main site. Maybe create a cron to run requests to main page every minute for 2-3 minutes and then die. Or something like that.
I want to make it as simple as possible without forcing people to read anything

**Comment by HesyRa** [comment]
I don't undestend for now, why its need several refreshes. When worked on logic I think one site refresh is more then enough. I can investigate this feature and fix it if possible. If I done that there are would be as much trouble as it is know. Should I work on this investigation @jimaek ?

**Comment by MartinKolarik** [comment]
Discussing in #10
