### ISSUE TITLE
Auto minification

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/plugin-wordpress#25]
Now that all our endpoints support minification, we should:
 - add an option "automatically minify files" (defaults to enabled)
 - in this plugin, use [this algorithm](https://github.com/MartinKolarik/is-minified-code/blob/master/index.js) to check if a local file is minified (for CSS/JS files) - if no, automatically rewrite the URL to a minified version (`file.example.js` -> `file.example.min.js`)
 - the existing file hash comparison should still compare original files, otherwise hashes wouldn't match - there's no need to verify the `.min` URLs separately

**Comment by HesyRa** [comment]
@MartinKolarik https://js.do/code/minified looks like this script run not at 100% cases

**Comment by MartinKolarik** [comment]
No, it's just a quick guess - it's ok if it returns a wrong result occasionally. jsDelivr backend uses it as a performance optimization to skip minifying files which already appear to be minified.
