### ISSUE TITLE
Compare file extension in addition to hash

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/plugin-wordpress#27]
While reviewing #26 I realized the lookup API could return a file which has the same content but different file extension. This could be a problem because different extension means different mime-type sent by server and the file might not actually work the same way in the browser. We should check that the extensions of local and remote file match.

**Comment by HesyRa** [comment]
@MartinKolarik I don't undestend you full. Can you give an example?

**Comment by MartinKolarik** [comment]
It is possible that for a local file `style.css` our `/lookup` API returns a file `style.txt` with the same content. That file however wouldn't load in most browsers because it would be served with `Content-Type: text/plain`. We need to check that extensions of both files are the same.

**Comment by HesyRa** [comment]
Thnx. Undestood.
