### ISSUE TITLE
Rename Automatically enable

### ISSUE THREAD

**Issue by jimaek** [jsdelivr/plugin-wordpress#9]
I suggest using "Keep everything synced automatically"

**Comment by MartinKolarik** [comment]
Maybe go back to short "Autosync" and add explanatory text: Automatically use jsDelivr links for all newly found files. If disabled, you'll need to manually enable any new files here.

**Comment by jimaek** [comment]
Its going to be the only setting the user can enable. So we can make it larger than usual. I want to see what the designer will come up with first.

**Comment by MartinKolarik** [comment]
Ok but either way we'll need the full text too.

**Comment by MartinKolarik** [comment]
#10
